### ISSUE TITLE
Edge guide

### ISSUE THREAD

**Issue by Sneezry** [Authenticator-Extension/authenticator.cc#20]
Since we have removed the extension from Microsoft store, we need a new guide for Edge users to install the extension from Chrome Web Store. And change the install button for Edge to point to the doc link.

**Comment by mymindstorm** [comment]
Yep, plan to do that later this week.

**Comment by 29039** [comment]
As per https://github.com/Authenticator-Extension/Authenticator/issues/710

Maybe you could get Microsoft to re-list it by calling it "Authenticator.cc" rather than "Authenticator", to differentiate it.

**Comment by Sneezry** [comment]
We have an issue to discuss about renaming https://github.com/Authenticator-Extension/Authenticator/issues/718

But we do not guarantee to continue maintaining Edge version. Edge users can install the extension from Chrome Web Store, and I don't find a strong reason to maintain a standalone version for Edge.

**Comment by mymindstorm** [comment]
Sorry that I haven't been able to get to this, am very busy at the moment.

**Comment by Sneezry** [comment]
I have updated the site, and redirect Edge button to https://authenticator.cc/docs/en/edge-install
