### ISSUE TITLE
recovery

### ISSUE THREAD

**Issue by jdrabikcombo** [Authenticator-Extension/authenticator.cc#30]
FireFox actualisation removed my Authenticator.cc extenstion on my browser. I lost access to my Facebook code.
Facebook Support insisted that i should contact Authenticator Help Center.
https://authenticator.cc/docs/en/lost-codes.html - this instruction does not work. Facebook needs authenticator code to change any settings. Could you please generate new code for me? / Recover my Authenticator account and codes?
I dont have any backup file.
Code which i need is for my Facebook account: roza.poleska@gmail.com

**Comment by Yessika224** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by mymindstorm** [comment]
Facebook support needs to recover your account. We cannot do anything if you do not have a backup. 

https://m.facebook.com/help/147926301947841
